### ISSUE TITLE
proxy加几个

### ISSUE THREAD

**Issue by xianren78** [2dust/v2rayCustomRoutingList#2]
##91porn 视频
185.38.13.0/24,
192.240.120.0/24,

##MyList
domain:popo8.com,
domain:x6img.com,
domain:vxotu.com,
domain:e2bo.com,
domain:xwbo.com,
domain:toutyrater.github.io,
domain:skuimg.com,
domain:touimg.com,
domain:6park.com,
domain:backchina.com,
domain:sexinsex.net,
domain:t66y.com,
domain:dwnews.com,

**Comment by 2dust** [comment]
你所列出的已经被自动代理了
我们想要的是在选择绕过大陆设置时,被错误绕过的cn域名,比如google.cn

**Comment by xianren78** [comment]
> 你所列出的已经被自动代理了
> 我们想要的是在选择绕过大陆设置时,被错误绕过的cn域名,比如google.cn

和bifrostv中我自己的设置搞混了，ng默认路由只能走proxy，不走direct。那这样可能需要列出在proxy里面的确实没有几个了。
