### ISSUE TITLE
路由设置无效

### ISSUE THREAD

**Issue by LiXin-x** [2dust/v2rayCustomRoutingList#3]
### 请见谅

作者你好，
首先 issue 可能不符合指引，按自己习惯直接提了，抱歉。
刚入门，但我自己通过 Google 和 v2ray 官网尝试了 6 个小时，仍然没有解决我的问题。
希望您能帮助我一下，我现在毫无头绪，谢谢。

### PC 环境

- v2ray-core 4.10
- v2rayN 2.21
- win10 1809
- chrome 71 or edge
- 福建移动宽带

### 问题

使用默认的自定义规则，在 PAC 模式无法访问

- facebook.com,
- youtube.com,
- github.com,
- github.io

google，Instagram 访问正常
全局模式下除 facebook 都可正常访问
同一 WiFi 网络下，手机上的 v2rayNG 以上所有网站都正常访问

### 尝试

在代理 domain 配置
`domain:youtube.com`
youtube.com 可正常访问

### 不明白

但是，配置

```
domain:github.com,
domain:github.io
```

均无法访问，显示

```
This site can’t be reached
github.com took too long to respond.
Try:
Checking the connection
Checking the proxy and the firewall
Running Windows Network Diagnostics
ERR_CONNECTION_TIMED_OUT
```

我在 chrome dev 观察到类似 google.com 是能够通过 127.0.0.1:1081 来转发，
但是 github.com 并不能，偶尔能够解析到 GitHub 的真实 IP。

**Comment by 2dust** [comment]
请自己看core文档,然后手写配置测试
如果你发现N或者NG产生的配置有问题,可以提到对应项目中
